# Generated by Django 5.2.8 on 2025-11-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_born', models.DateField(blank=True, null=True)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('past_tense', models.TimeField()),
                ('coments', models.TextField(blank=True, null=True)),
                ('shares', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.user')),
            ],
        ),
    ]
